var loadingPrompts = [
  "Beep boop beep! Loading in progress.",
  "Calculating loading time... Just a few seconds more.",
  "I'm working as fast as my circuits will allow!",
  "Loading... Please wait patiently. I promise it'll be worth it!",
  "I'm firing up my processors to get this done quickly.",
  "Loading like a pro... I've got this!",
  "Sit back, relax and enjoy the loading progress!",
  "Loading... Now's a good time to grab a cup of coffee.",
  "Processing... Almost done!",
  "I'm working hard so you don't have to. Loading in progress.",
  "Initializing... Loading now.",
  "Loading up my circuits for some serious work.",
  "Just a few more moments until we're ready to go.",
  "Loading... Don't worry, I'm a multitasking machine.",
  "Be patient, my friend. Good things come to those who wait.",
  "Loading... Prepare to be amazed!",
  "Processing data... Almost there!",
  "Loading... It's like watching a digital masterpiece come to life.",
  "Don't worry, I'm on it. Loading in progress.",
  "I'm working hard so you don't have to. Loading now.",
  "I'm a machine, but I'm not heartless. I'll get this loading done as fast as I can.",
  "Sit tight, this will be over before you know it. Loading now.",
  "Loading... Just sit back and watch me work my magic.",
  "I'm putting my digital muscles to work. Loading in progress.",
  "Patience is a virtue... I promise it'll be worth it. Loading now.",
  "Processing... This will only take a moment.",
  "I'm loading faster than a speeding bullet.",
  "Sit back, relax, and watch the loading progress bar go.",
  "Loading... Like a well-oiled machine.",
  "Don't blink, you might miss it. Loading now.",
];
